[package]
name = "workshop"
version = "1.0.0"
edition = "2023_01"

[dependencies]
starknet=">=2.8.4"

[dev-dependencies]
cairo_test = "2.8.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.32.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm=true